# Text from Microsoft Learn (en-us) module landing pages — summary, objectives, units, prerequisites.
# https://learn.microsoft.com/en-us/training/modules/<slug>/

LEARN = {
    "explore-azure-pipelines": {
        "summary": "Learn what Azure Pipelines is, how it helps automate your development workflow, and key concepts you need to get started with building and deploying applications.",
        "objectives": [
            "Understand what Azure Pipelines is and how it helps your team.",
            "Explain key components and how they work together.",
            "Choose the right automation approach for your projects.",
            "Use essential Azure Pipelines terminology with confidence.",
        ],
        "units": [
            "Introduction",
            "Explore the concept of pipelines in DevOps",
            "Describe Azure Pipelines",
            "Understand Azure Pipelines key terms",
            "Module assessment",
            "Summary",
        ],
    },
    "manage-azure-pipeline-agents-pools": {
        "summary": "This module explores the differences between Microsoft-hosted and self-hosted agents, details job types, and configures agent pools. Understand typical situations to use agent pools and how to manage their security.",
        "objectives": [
            "Choose between Microsoft-hosted and self-hosted agents.",
            "Install and configure Azure Pipelines Agents.",
            "Configure agent pools.",
            "Make the agents and pools secure.",
            "Explore communication to deploy using Azure Pipelines.",
        ],
        "units": [
            "Introduction",
            "Choose between Microsoft-hosted versus self-hosted agents",
            "Explore job types",
            "Introduction to agent pools",
            "Explore predefined agent pool",
            "Understand typical situations for agent pools",
            "Communicate with Azure Pipelines",
            "Communicate to deploy to target servers",
            "Examine other considerations",
            "Describe security of agent pools",
            "Configure agent pools and understand pipeline styles",
            "Module assessment",
            "Summary",
        ],
    },
    "describe-pipelines-concurrency": {
        "summary": "This module describes parallel jobs and how to estimate their usage. Also, it presents Azure Pipelines for open-source projects, explores Visual Designer and YAML pipelines.",
        "objectives": [
            "Use and estimate parallel jobs.",
            "Use Azure Pipelines for open-source or private projects.",
            "Use Visual Designer.",
            "Work with Azure Pipelines and YAML.",
        ],
        "units": [
            "Introduction",
            "Understand parallel jobs",
            "Estimate parallel jobs",
            "Describe Azure Pipelines and open-source projects",
            "Explore Azure Pipelines and Visual Designer",
            "Describe Azure Pipelines and YAML",
            "Enable Continuous Integration with Azure Pipelines",
            "Module assessment",
            "Summary",
        ],
    },
    "implement-pipeline-strategy": {
        "summary": "Learn how to design and implement effective pipeline strategies using Azure Pipelines. This module covers agent demands, multi-configuration builds, GitHub integration, testing strategies, code coverage, and source control options.",
        "objectives": [
            "Design and implement effective build strategies",
            "Configure and manage agent demands",
            "Implement multi-configuration and multi-agent builds",
            "Integrate GitHub repositories with Azure Pipelines",
            "Design comprehensive testing strategies",
            "Implement code coverage in pipeline workflows",
            "Use different source control types available in Azure Pipelines",
        ],
        "units": [
            "Introduction",
            "Configure agent demands",
            "Explore multi-configuration and multi-agent builds",
            "Integrate GitHub repositories with Azure Pipelines",
            "Design and implement a comprehensive testing strategy",
            "Implement code coverage and show in the pipeline",
            "Implement multi-job builds",
            "Explore source control types supported by Azure Pipelines",
            "Knowledge check",
            "Summary",
        ],
    },
    "integrate-azure-pipelines": {
        "summary": "Learn Azure Pipelines integration by exploring advanced pipeline anatomy, structure, templates, YAML resources, and multi-repository workflows. Build effective CI/CD solutions using modern pipeline practices.",
        "objectives": [
            "Understand advanced Azure Pipelines anatomy and structure",
            "Create and use pipeline templates for code reuse",
            "Work with YAML resources and dependencies",
            "Implement multi-repository workflows in your pipelines",
            "Apply modern pipeline integration patterns and best practices",
        ],
        "units": [
            "Introduction",
            "Describe the anatomy of a pipeline",
            "Understand the pipeline structure",
            "Detail templates",
            "Explore YAML resources",
            "Use multiple repositories in your pipeline",
            "Migrate a pipeline from classic to YAML in Azure Pipelines",
            "Module assessment",
            "Summary",
        ],
    },
    "introduction-to-github-actions": {
        "summary": "Learn GitHub Actions fundamentals including workflows, events, jobs, and runners. Discover how to automate your development processes and read console output from actions.",
        "objectives": [
            "Understand GitHub Actions and workflows",
            "Create and work with GitHub Actions and workflows",
            "Work with events, jobs, and runners",
            "Read output and manage releases for actions",
        ],
        "units": [
            "Introduction",
            "What are actions?",
            "Explore actions flow",
            "Understand workflows",
            "Describe standard workflow syntax elements",
            "Explore events",
            "Explore jobs",
            "Explore runners",
            "Examine release and test an action",
            "Module assessment",
            "Summary",
        ],
    },
    "learn-continuous-integration-github-actions": {
        "summary": "Learn continuous integration with GitHub Actions by implementing workflows, managing environment variables and artifacts, creating secure secrets, and following industry best practices for robust CI/CD pipelines.",
        "objectives": [
            "Design and implement continuous integration workflows with GitHub Actions",
            "Configure environment variables and manage workflow data securely",
            "Share artifacts between jobs and automate release management with Git tags",
            "Create and manage encrypted secrets for secure CI/CD operations",
            "Apply industry best practices for maintainable and scalable automation pipelines",
        ],
        "units": [
            "Introduction",
            "Describe continuous integration with Actions",
            "Examine environment variables",
            "Share artifacts between jobs",
            "Examine workflow badges",
            "Describe best practices for creating actions",
            "Mark releases with Git tags",
            "Create encrypted secrets",
            "Use secrets in a workflow",
            "Implement GitHub Actions for CI/CD",
            "Module assessment",
            "Summary",
        ],
    },
    "design-container-build-strategy": {
        "summary": "Learn to plan container build strategies, work with Docker containers, and deploy containerized applications using Azure services.",
        "objectives": [
            "Design effective container build strategies",
            "Work with Docker containers and Dockerfiles",
            "Implement multi-stage builds and best practices",
            "Deploy containers to Azure services",
        ],
        "units": [
            "Introduction",
            "Examine structure of containers",
            "Work with Docker containers",
            "Understand Dockerfile core concepts",
            "Examine multi-stage Dockerfiles",
            "Examine considerations for multiple stage builds",
            "Explore Azure container-related services",
            "Deploy Docker containers to Azure App Service web apps",
            "Module assessment",
            "Summary",
        ],
    },
    "create-release-pipeline-devops": {
        "summary": "Learn Azure Pipelines capabilities, build and release tasks, and deployment workflows.",
        "objectives": [
            "Explain Azure Pipelines release management terminology and concepts.",
            "Describe build and release tasks and their deployment capabilities.",
            "Implement release jobs and configure deployment workflows.",
        ],
        "units": [
            "Introduction",
            "Describe Azure Pipelines capabilities",
            "Explore release pipelines",
            "Explore artifact sources",
            "Choose the appropriate artifact source",
            "Examine considerations for deployment to stages",
            "Explore build and release tasks",
            "Explore custom build and release tasks",
            "Explore release jobs",
            "Understand database deployment task",
            "Configure pipelines as code with YAML",
            "Module assessment",
            "Summary",
        ],
    },
    "explore-release-strategy-recommendations": {
        "summary": "Learn critical release strategy recommendations for automated deployments. Understand release pipeline components, artifact sources, approval workflows, and release gate configurations.",
        "objectives": [
            "Analyze key considerations for designing effective release strategies.",
            "Define release pipeline components and configure artifact sources.",
            "Create comprehensive release approval workflows.",
            "Implement and configure release gates for quality assurance.",
        ],
        "units": [
            "Introduction",
            "Understand the delivery cadence and three types of triggers",
            "Explore release approvals",
            "Explore release gates",
            "Use release gates to protect quality",
            "Explore GitOps release strategy and recommendations",
            "Control deployments using release gates",
            "Module assessment",
            "Summary",
        ],
    },
    "configure-provision-environments": {
        "summary": "Learn target environment provisioning, service connection configuration, and test infrastructure setup. Configure functional test automation and implement availability testing strategies.",
        "objectives": [
            "Provision and configure target environments for deployment workflows.",
            "Deploy securely to environments using service connections.",
            "Configure functional test automation and implement availability testing.",
            "Set up comprehensive test infrastructure for quality assurance.",
        ],
        "units": [
            "Introduction",
            "Provision and configure target environments",
            "Exercise - set up service connections",
            "Configure automated integration and functional test automation",
            "Understand Shift-left",
            "Set up and run availability tests",
            "Explore Azure Load Testing",
            "Set up and run functional tests",
            "Module assessment",
            "Summary",
        ],
    },
    "manage-modularize-tasks-templates": {
        "summary": "This module explores task group creation, variable group management, and custom build and release task development for scalable pipeline architectures.",
        "objectives": [
            "Create and manage task groups for reusable pipeline components.",
            "Implement variable groups for centralized configuration management.",
            "Configure release variables and stage variables for environment-specific deployments.",
            "Develop custom build and release tasks for specialized pipeline requirements.",
        ],
        "units": [
            "Introduction",
            "Examine task groups",
            "Explore Variables in release pipelines",
            "Exercise - Create and manage variable groups",
            "Module assessment",
            "Summary",
        ],
    },
    "automate-inspection-health": {
        "summary": "This module explores automated health event monitoring, notification configuration across Azure DevOps and GitHub platforms, service hook implementation for pipeline oversight, and quality measurement frameworks for robust release management processes.",
        "objectives": [
            "Implement automated health inspection systems for continuous monitoring and proactive issue detection.",
            "Create and configure event-driven notification systems for real-time pipeline feedback.",
            "Configure comprehensive notification frameworks across Azure DevOps and GitHub platforms.",
            "Develop service hooks for automated pipeline monitoring and integration workflows.",
            "Distinguish between release artifacts and release processes while implementing quality control mechanisms.",
            "Evaluate and select appropriate release management tools for organizational requirements.",
        ],
        "units": [
            "Introduction",
            "Automate inspection of health",
            "Explore events and notifications",
            "Explore service hooks",
            "Configure Azure DevOps notifications",
            "Configure GitHub notifications",
            "Explore how to measure quality of your release process",
            "Examine release notes and documentation",
            "Examine considerations for choosing release management tools",
            "Explore common release management tools",
            "Module assessment",
            "Summary",
        ],
    },
    "introduction-to-deployment-patterns": {
        "summary": "This module delivers comprehensive deployment pattern analysis through microservices architecture exploration, classical deployment methodology examination, and modern continuous delivery strategy implementation for optimized release cycle management.",
        "objectives": [
            "Analyze deployment pattern architectures and implementation strategies",
            "Evaluate microservices architecture principles and distributed system design",
            "Compare classical and modern deployment patterns for optimal release strategies",
            "Design scalable deployment architectures aligned with organizational requirements",
        ],
        "units": [
            "Introduction",
            "Explore microservices architecture",
            "Examine classical deployment patterns",
            "Understand modern deployment patterns",
            "Module assessment",
            "Summary",
        ],
    },
    "implement-blue-green-deployment-feature-toggles": {
        "summary": "This module delivers comprehensive blue-green deployment methodology implementation and feature toggle architecture design for controlled progressive delivery, zero-downtime releases, and dynamic feature management.",
        "objectives": [
            "Analyze advanced deployment strategies and progressive delivery patterns",
            "Implement blue-green deployment architectures for zero-downtime releases",
            "Configure and manage Azure deployment slots for environment isolation",
            "Design and implement feature toggle systems for dynamic feature control",
        ],
        "units": [
            "Introduction",
            "What is blue-green deployment?",
            "Explore deployment slots",
            "Introduction to feature toggles",
            "Describe feature toggle maintenance",
            "Module assessment",
            "Summary",
        ],
    },
    "implement-canary-releases-dark-launching": {
        "summary": "This module delivers comprehensive canary release implementation strategies, Azure Traffic Manager configuration for gradual traffic shifting, and dark launching methodologies for risk-mitigated progressive delivery.",
        "objectives": [
            "Analyze progressive deployment strategies and incremental rollout patterns",
            "Implement canary release architectures with gradual traffic migration",
            "Configure Azure Traffic Manager for intelligent traffic distribution",
            "Design dark launching strategies for hidden feature validation",
        ],
        "units": [
            "Introduction",
            "Explore canary releases",
            "Examine traffic manager",
            "Understand dark launching",
            "Module assessment",
            "Summary",
        ],
    },
    "implement-test-progressive-exposure-deployment": {
        "summary": "This module delivers comprehensive A/B testing implementation strategies, progressive exposure deployment patterns, and ring-based CI/CD architectures for data-driven feature validation and phased rollout orchestration.",
        "objectives": [
            "Design progressive exposure deployment strategies with phased user cohort targeting",
            "Implement A/B testing frameworks for data-driven feature validation",
            "Configure ring-based deployment architectures for controlled CI/CD rollouts",
            "Analyze deployment strategy tradeoffs and select optimal patterns",
        ],
        "units": [
            "Introduction",
            "What is A/B testing?",
            "Explore CI/CD with deployment rings",
            "Module assessment",
            "Summary",
        ],
    },
    "integrate-identity-management-systems": {
        "summary": "This module delivers comprehensive identity integration strategies encompassing GitHub single sign-on (SSO) authentication, Microsoft Entra ID workload identities, service principal provisioning, and managed identity implementations for secure DevOps workflows.",
        "objectives": [
            "Integrate Azure DevOps with Microsoft Entra ID identity management architectures",
            "Implement GitHub single sign-on (SSO) and multifactor authentication strategies",
            "Design and provision service principals for workload identity scenarios",
            "Configure managed identities for passwordless Azure resource authentication",
        ],
        "units": [
            "Introduction",
            "Integrate GitHub with single sign-on (SSO)",
            "Design and implement permissions and roles in GitHub",
            "Design and implement permissions and security groups in Azure DevOps",
            "Explore workload identities",
            "Implement managed identities",
            "Module assessment",
            "Summary",
        ],
    },
    "manage-application-configuration-data": {
        "summary": "This module delivers comprehensive configuration management strategies encompassing externalized configuration patterns, separation of concerns architectures, Azure App Configuration implementation, Key Vault secret management integration, and dynamic feature flag orchestration for secure, maintainable application settings.",
        "objectives": [
            "Design externalized configuration architectures implementing separation of concerns principles",
            "Implement Azure App Configuration with key-value pair management and labeling strategies",
            "Integrate Azure Key Vault with Azure Pipelines for secure secret management",
            "Configure feature flags and dynamic configuration for progressive feature rollouts",
            "Manage secrets, tokens, and certificates following DevOps security best practices",
            "Implement external configuration store patterns for distributed applications",
        ],
        "units": [
            "Introduction",
            "Rethink application configuration data",
            "Explore separation of concerns",
            "Understand external configuration store patterns",
            "Implement Azure DevOps secure files",
            "Introduction to Azure App Configuration",
            "Examine key-value pairs",
            "Examine App Configuration feature management",
            "Integrate Azure Key Vault with Azure Pipelines",
            "Manage secrets, tokens, and certificates",
            "Examine DevOps inner and outer loop",
            "Integrate Azure Key Vault with Azure DevOps",
            "Enable dynamic configuration and feature flags",
            "Module assessment",
            "Summary",
        ],
    },
    "explore-infrastructure-code-configuration-management": {
        "summary": "This module examines Infrastructure as Code (IaC) foundational concepts encompassing environment deployment provisioning and configuration management methodologies. Content explores imperative versus declarative configuration approaches, idempotent configuration principles, and organizational implementation strategies enabling automated infrastructure operations with version control, consistency, and reproducibility.",
        "objectives": [
            "Implement environment deployment automation strategies using Infrastructure as Code",
            "Design environment configuration management approaches with version control",
            "Differentiate between imperative and declarative configuration methodologies",
            "Apply idempotent configuration principles ensuring consistent infrastructure operations",
        ],
        "prerequisites": [
            "Understanding of DevOps principles and practices",
            "Familiarity with version control systems",
            "Basic knowledge of cloud computing concepts",
        ],
        "units": [
            "Introduction",
            "Explore environment deployment",
            "Examine environment configuration",
            "Understand imperative versus declarative configuration",
            "Understand idempotent configuration",
            "Module assessment",
            "Summary",
        ],
    },
    "create-azure-resources-using-azure-resource-manager-templates": {
        "summary": "This module explores Azure Resource Manager templates (ARM templates) and their components, teaching you how to create declarative infrastructure as code. Learn to manage dependencies, modularize templates for reusability, and securely handle secrets with Azure Key Vault integration. Discover both JSON ARM templates and modern Bicep syntax for efficient Azure resource deployment.",
        "objectives": [
            "Create and deploy Azure resources using ARM templates and Bicep syntax.",
            "Understand ARM template components including parameters, variables, functions, resources, and outputs.",
            "Manage resource dependencies using dependsOn element and reference functions.",
            "Organize and modularize templates using linked and nested templates for reusability.",
            "Securely manage secrets and sensitive values through Azure Key Vault integration.",
            "Choose appropriate deployment modes (incremental vs. complete) for different scenarios.",
        ],
        "prerequisites": [
            "Understanding of DevOps practices and continuous deployment concepts.",
            "Familiarity with Azure services and resource management.",
            "Basic knowledge of JSON format and declarative syntax.",
            "Experience with infrastructure as code (IaC) concepts is beneficial.",
        ],
        "units": [
            "Introduction",
            "Why use Azure Resource Manager templates?",
            "Explore template components",
            "Manage dependencies",
            "Modularize templates",
            "Manage secrets in templates",
            "Module assessment",
            "Summary",
        ],
    },
    "create-azure-resources-by-using-azure-cli": {
        "summary": "This module teaches you how to use the Azure Command-Line Interface (CLI) to create and manage Azure resources efficiently. Learn to install Azure CLI across Windows, Linux, and macOS, execute commands interactively, create Bash automation scripts, and troubleshoot common issues. Discover best practices for authentication, resource group management, and storage account creation using this powerful cross-platform tool.",
        "objectives": [
            "Install Azure CLI: Set up Azure CLI on Linux, macOS, and Windows operating systems.",
            "Authenticate to Azure: Log into Azure using various methods including interactive login, managed identities, and service principals.",
            "Understand CLI syntax: Learn Azure CLI command structure including reference groups, commands, parameters, and values.",
            "Create resources interactively: Execute Azure CLI commands at the terminal to create resource groups and storage accounts.",
            "Automate with scripts: Write and execute Bash scripts that leverage Azure CLI for automated resource management.",
            "Troubleshoot effectively: Use the --debug parameter and understand scripting language differences to resolve common issues.",
        ],
        "prerequisites": [
            "Command-line experience: Familiarity with Bash, PowerShell, or similar command-line interfaces.",
            "Azure fundamentals: Basic understanding of Azure concepts including resource groups, storage accounts, and subscriptions.",
            "Azure portal experience: Practical experience managing Azure resources through the Azure portal.",
            "DevOps awareness: General knowledge of automation and infrastructure management practices.",
        ],
        "units": [
            "Introduction",
            "What Is Azure CLI?",
            "Install Azure CLI",
            "Execute Azure CLI Commands Interactively",
            "Create an Azure CLI Script for Bash",
            "Tips to Use the Azure CLI Successfully",
            "Module assessment",
            "Summary",
        ],
    },
    "explore-azure-automation-devops": {
        "summary": "Learn how to implement Azure Automation with DevOps using runbooks, webhooks, and PowerShell workflows. Understand how to create automation accounts, manage shared resources, integrate with source control systems, and plan for hybrid cloud management across Azure and on-premises environments.",
        "objectives": [
            "Create and configure Azure Automation accounts for managing cloud resources.",
            "Implement and manage runbooks using PowerShell, PowerShell Workflow, Python, and graphical editors.",
            "Configure webhooks to trigger runbooks from external systems and services.",
            "Integrate Azure Automation with GitHub and Azure DevOps for version control and CI/CD.",
            "Create and execute PowerShell workflows with checkpoints and parallel processing.",
            "Plan and implement hybrid management using Azure Automation across cloud and on-premises resources.",
        ],
        "prerequisites": [
            "Understanding of DevOps concepts and practices.",
            "Familiarity with PowerShell scripting and command-line interfaces.",
            "Basic knowledge of Azure services and resource management.",
            "Experience with version control systems (Git or Team Foundation Version Control).",
        ],
        "units": [
            "Introduction",
            "Create automation accounts",
            "What is a runbook?",
            "Understand automation shared resources",
            "Explore runbook gallery",
            "Examine webhooks",
            "Explore source control integration",
            "Explore PowerShell workflows",
            "Create a workflow",
            "Explore hybrid management",
            "Examine checkpoint and parallel processing",
            "Module assessment",
            "Summary",
        ],
    },
    "implement-desired-state-configuration-dsc": {
        "summary": "This module describes Desired State Configuration (DSC) and its components for implementation with Azure Automation. Learn to manage configuration drift, create DSC configurations, implement DSC for Linux environments, and plan for hybrid management scenarios.",
        "objectives": [
            "Understand and manage configuration drift in your infrastructure.",
            "Implement Desired State Configuration (DSC) with PowerShell.",
            "Describe Azure Automation State Configuration and its components.",
            "Create and manage DSC configuration files.",
            "Implement DSC and Linux automation on Azure.",
            "Plan for hybrid management with DSC.",
        ],
        "prerequisites": [
            "Understanding of Azure Automation and automation accounts.",
            "Basic knowledge of PowerShell scripting.",
            "Familiarity with infrastructure as code concepts.",
            "Experience with Azure resources and virtual machines.",
        ],
        "units": [
            "Introduction",
            "Understand configuration drift",
            "Explore Desired State Configuration (DSC)",
            "Explore Azure Automation State Configuration (DSC)",
            "Examine DSC configuration file",
            "Implement DSC and Linux automation on Azure",
            "Module assessment",
            "Summary",
        ],
    },
    "implement-bicep": {
        "summary": "This module explains Bicep and how it integrates with different tools such as Azure CLI, Visual Studio Code, Azure Pipelines, and GitHub workflows for infrastructure as code deployment. Learn to create, deploy, and manage Azure resources using Bicep templates.",
        "objectives": [
            "Understand what Bicep is and its benefits for infrastructure as code.",
            "Install Bicep and configure a smooth authoring experience with Visual Studio Code.",
            "Create Bicep templates to define Azure resources.",
            "Understand Bicep file structure, syntax, parameters, variables, and modules.",
            "Deploy Bicep files using Azure CLI and Cloud Shell.",
            "Deploy Bicep templates from Azure Pipelines for continuous deployment.",
            "Deploy Bicep templates from GitHub workflows for automated deployments.",
            "Understand how Bicep integrates with Azure Resource Manager templates.",
        ],
        "prerequisites": [
            "Understanding of infrastructure as code concepts.",
            "Basic knowledge of Azure resources and resource groups.",
            "Familiarity with Azure CLI or Azure PowerShell.",
            "Experience with Azure Pipelines or GitHub workflows is helpful but not required.",
        ],
        "units": [
            "Introduction",
            "What is Bicep?",
            "Install Bicep",
            "Exercise - Create Bicep templates",
            "Understand Bicep file structure and syntax",
            "Exercise - Deploy a Bicep file from Azure Pipelines",
            "Exercise - Deploy a Bicep file from GitHub workflows",
            "Deployments using Azure Bicep templates",
            "Module assessment",
            "Summary",
        ],
    },
    "explore-package-dependencies": {
        "summary": "This module explores dependency management concepts and helps you identify project dependencies. You'll learn how to decompose your system, identify dependencies, understand package componentization, and scan your codebase for dependencies. Gain practical knowledge of dependency management strategies using Azure Artifacts, NuGet, npm, and Maven to manage software components effectively.",
        "objectives": [
            "Define dependency management strategy: Understand the principles and benefits of managing dependencies in modern software development.",
            "Identify dependencies: Recognize and categorize dependencies in your projects and solutions.",
            "Describe elements and componentization of dependency management: Understand how to decompose systems into manageable components.",
            "Scan your codebase for dependencies: Use tools and techniques to discover and analyze dependencies in your source code.",
        ],
        "prerequisites": [
            "Understanding of what DevOps is and its concepts",
            "Familiarity with version control principles",
            "Basic knowledge of software development and project structure",
            "Experience working with packages and libraries is helpful but not required",
        ],
        "units": [
            "Introduction",
            "What is dependency management?",
            "Describe elements of a dependency management strategy",
            "Identify dependencies",
            "Understand source and package componentization",
            "Decompose your system",
            "Scan your codebase for dependencies",
            "Module assessment",
            "Summary",
        ],
    },
    "understand-package-management": {
        "summary": "This module describes package management fundamentals including package feeds, package feed managers, common public package sources, self-hosted and SaaS-based solutions, and practical guidance for consuming, creating, and publishing packages using Azure Artifacts and other package management tools.",
        "objectives": [
            "Understand packages and package management concepts",
            "Implement and manage package feeds with public and private sources",
            "Explore package feed managers and hosting options",
            "Consume packages from various sources in your projects",
            "Create and publish packages to Azure Artifacts and other feeds",
        ],
        "prerequisites": [
            "Basic understanding of software development and dependencies",
            "Familiarity with version control systems",
            "General knowledge of build and deployment processes",
            "Access to an Azure DevOps organization (recommended for hands-on practice)",
        ],
        "units": [
            "Introduction",
            "Explore packages",
            "Understand package feeds",
            "Explore package feed managers",
            "Explore common public package sources",
            "Explore self-hosted and SaaS-based package sources",
            "Consume packages",
            "Introduction to Azure Artifacts",
            "Publish packages",
            "Package management with Azure Artifacts",
            "Module assessment",
            "Summary",
        ],
    },
    "migrate-consolidating-secure-artifacts": {
        "summary": "This module details package migration strategies, artifact repository consolidation approaches, and comprehensive security configuration to secure access to package feeds and artifact repositories using Azure Artifacts roles, permissions, and authentication mechanisms.",
        "objectives": [
            "Identify existing artifact repositories across your organization and assess migration needs",
            "Migrate and integrate artifact repositories into Azure Artifacts using appropriate strategies",
            "Secure package feeds with proper access control and visibility settings",
            "Implement roles to control feed access at different levels (Reader, Collaborator, Contributor, Owner)",
            "Configure granular permissions for users, teams, and service principals",
            "Set up authentication mechanisms including Personal Access Tokens and credential providers",
        ],
        "prerequisites": [
            "Understanding of package management concepts and Azure Artifacts fundamentals",
            "Familiarity with Azure DevOps organizations and projects",
            "Basic knowledge of authentication and authorization concepts",
            "Experience with at least one package type (NuGet, npm, Maven, or Python)",
        ],
        "units": [
            "Introduction",
            "Identify existing artifact repositories",
            "Migrate and integrate artifact repositories",
            "Secure access to package feeds",
            "Examine roles",
            "Examine permissions",
            "Examine authentication",
            "Module assessment",
            "Summary",
        ],
    },
    "implement-versioning-strategy": {
        "summary": "This module explains versioning strategies for packaging, semantic versioning principles, package promotion workflows, and best practices for managing package versions throughout the software development lifecycle. Learn to use Azure Artifacts views to indicate package quality and implement automated versioning in CI/CD pipelines.",
        "objectives": [
            "Understand the importance of versioning for package management and dependency tracking",
            "Implement semantic versioning (SemVer 2.0) for consistent version numbering",
            "Use Azure Artifacts views (@Local, @Prerelease, @Release) to manage package quality",
            "Promote packages through different views based on quality levels",
            "Push packages from build pipelines with appropriate version numbers",
            "Apply best practices for versioning strategies in DevOps workflows",
        ],
        "prerequisites": [
            "Basic understanding of DevOps concepts and CI/CD pipelines",
            "Familiarity with package management and dependency management principles",
            "Experience with Azure DevOps or similar CI/CD platforms",
            "Knowledge of software versioning concepts is beneficial",
        ],
        "units": [
            "Introduction",
            "Understand versioning of artifacts",
            "Explore semantic versioning",
            "Examine release views",
            "Promote packages",
            "Explore best practices for versioning",
            "Module assessment",
            "Summary",
        ],
    },
    "introduction-github-packages": {
        "summary": "This module introduces you to GitHub Packages, a package hosting service fully integrated with GitHub. Learn how to publish packages from repositories, install packages in projects, manage package lifecycle through deletion and restoration, and control access using permissions and visibility settings. Understand authentication methods and best practices for secure package management.",
        "objectives": [
            "Publish packages to GitHub Packages from repositories and CI/CD workflows",
            "Install packages from GitHub Packages in development and production environments",
            "Delete and restore packages using GitHub web interface and API",
            "Configure access control and visibility for public, private, and internal packages",
            "Authenticate to GitHub Packages using personal access tokens (PATs)",
            "Understand supported package registries (npm, Docker, NuGet, Maven, RubyGems)",
        ],
        "prerequisites": [
            "Basic understanding of package management concepts and version control with Git",
            "Familiarity with GitHub repositories, workflows, and Actions",
            "Knowledge of at least one package ecosystem (npm, NuGet, Maven, or Docker)",
            "Experience with command-line tools and package managers",
        ],
        "units": [
            "Introduction",
            "Publish packages",
            "Install a package",
            "Delete and restore a package",
            "Explore package access control and visibility",
            "Module assessment",
            "Summary",
        ],
    },
    "implement-tools-track-usage-flow": {
        "summary": "This module introduces you to continuous feedback practices and monitoring tools essential for tracking application usage and flow. Learn how to implement Azure Monitor, Log Analytics, and Application Insights to gain deep insights into application performance, user behavior, and system health. Explore Kusto Query Language (KQL) for powerful data analysis and understand the inner loop development workflow for faster feedback cycles.",
        "objectives": [
            "Implement tools to track feedback and telemetry data from applications",
            "Plan for continuous monitoring strategies across development and production environments",
            "Implement Application Insights for comprehensive application performance monitoring",
            "Use Kusto Query Language (KQL) to query and analyze telemetry data",
            "Design and implement metrics and queries for actionable insights",
            "Monitor application performance using Azure Monitor and Log Analytics",
            "Understand the inner loop and outer loop development workflows",
        ],
        "prerequisites": [
            "Understanding of DevOps concepts and practices",
            "Familiarity with Azure portal and Azure services",
            "Basic knowledge of application development and deployment",
            "Experience with monitoring and logging concepts",
            "Understanding of CI/CD pipelines and automation",
        ],
        "units": [
            "Introduction",
            "Understand the Inner Loop",
            "Introduction to Continuous Monitoring",
            "Explore Azure Monitor and Log Analytics",
            "Examine Kusto Query Language (KQL)",
            "Explore Application Insights",
            "Implement Application Insights",
            "Design and Implement Metrics and Queries",
            "Monitor Application Performance with Azure Load Testing",
            "Module assessment",
            "Summary",
        ],
    },
    "develop-monitor-status-dashboards": {
        "summary": "This comprehensive module teaches you to develop effective monitoring and status dashboards for modern DevOps environments. You'll learn to use Azure Dashboards for integrated visualizations, Azure Monitor Workbooks for interactive reporting, and Power BI for advanced analytics. Learn to configure GitHub monitoring, track critical pipeline health metrics (failure rates, duration, flaky tests), and optimize pipeline performance for cost, time, and reliability. Discover strategies for building custom monitoring applications and implementing concurrency optimization to maximize throughput while controlling costs.",
        "objectives": [
            "Configure comprehensive monitoring in GitHub with status badges, insights, and Actions analytics",
            "Create and customize Azure Dashboards with pinned visualizations from multiple Azure services",
            "Develop interactive Azure Monitor Workbooks with parameters, queries, and custom visualizations",
            "Implement Power BI dashboards for advanced DevOps analytics and business intelligence",
            "Build custom monitoring applications using Azure DevOps REST APIs and Application Insights SDKs",
            "Monitor pipeline health metrics including failure rates, execution duration, and flaky test detection",
            "Optimize pipelines for cost, time, performance, and reliability using data-driven strategies",
            "Implement pipeline concurrency optimization to balance throughput performance with infrastructure costs",
            "Design effective visualization strategies that communicate system health to diverse stakeholders",
            "Establish alerting and notification systems based on dashboard metrics and threshold violations",
        ],
        "prerequisites": [
            "Fundamental understanding of Azure DevOps or GitHub workflows and CI/CD concepts",
            "Basic familiarity with Azure portal navigation and Azure Monitor fundamentals",
            "Experience with build and release pipelines in either Azure Pipelines or GitHub Actions",
            "Understanding of common DevOps metrics (build success rate, deployment frequency, lead time)",
            "Recommended: Completion of \"Implement tools to track usage and flow\" module for monitoring foundation",
        ],
        "units": [
            "Introduction",
            "Configure monitoring in GitHub",
            "Explore Azure dashboards",
            "Explore Azure Monitor workbooks",
            "Explore Power BI",
            "Build your own custom monitoring application",
            "Monitor pipeline health including failure rate, duration, and flaky tests",
            "Optimize pipelines for cost, time, performance, and reliability",
            "Optimize pipeline concurrency for performance",
            "Module assessment",
            "Summary",
        ],
    },
    "share-knowledge-within-teams": {
        "summary": "This module teaches you to establish effective knowledge sharing practices within development teams using Azure DevOps Wikis, GitHub documentation, and Microsoft Teams integration. Learn to create and manage project wikis, write documentation with Markdown and Mermaid diagrams, integrate DevOps tools with communication platforms, and implement strategies to preserve organizational knowledge as teams evolve. Discover how to avoid relearning lessons, reduce onboarding time, and improve team collaboration through structured documentation and real-time notifications.",
        "objectives": [
            "Implement knowledge sharing strategies to preserve organizational learning and reduce repeated mistakes",
            "Create and manage Azure DevOps project wikis with appropriate permissions and access control",
            "Write technical documentation using Markdown and GitHub Flavored Markdown (GFM) syntax",
            "Create diagrams in documentation using Mermaid syntax for flowcharts, sequence diagrams, and graphs",
            "Integrate GitHub with Microsoft Teams for notifications, pull request discussions, and issue management",
            "Integrate Azure DevOps Boards, Repos, and Pipelines with Microsoft Teams for unified collaboration",
            "Configure subscriptions, filters, and notifications for work items, pull requests, and pipeline events",
            "Establish documentation practices that support team onboarding, standards communication, and knowledge retention",
        ],
        "units": [
            "Introduction",
            "Share acquired knowledge within development teams",
            "Introduction to Azure DevOps project wikis",
            "Integrate GitHub and Azure DevOps with Microsoft Teams",
            "Share team knowledge using Azure project wiki",
            "Module assessment",
            "Summary",
        ],
    },
    "design-processes-automate-application-analytics": {
        "summary": "This module teaches you to design automated analytics processes for modern applications. Learn to implement Application Insights, integrate telemetry data, use augmented search for rapid problem identification, and select appropriate monitoring tools to ensure application health and optimal user experience in fast-paced DevOps environments.",
        "objectives": [
            "Design automated application analytics processes using Azure Application Insights.",
            "Implement augmented search strategies for rapid incident response and root cause analysis.",
            "Integrate telemetry data collection across applications and infrastructure.",
            "Select and configure monitoring tools with advanced capabilities for continuous application monitoring.",
            "Connect ITSM tools with Azure monitoring services for streamlined incident management.",
        ],
        "units": [
            "Introduction",
            "Explore rapid responses and augmented search",
            "Integrate telemetry",
            "Examine monitoring tools and technologies",
            "Explore IT Service Management Connector",
            "Module assessment",
            "Summary",
        ],
    },
    "manage-alerts-blameless-retrospectives-just-culture": {
        "summary": "This module teaches you to manage monitoring alerts effectively, conduct blameless retrospectives that focus on learning rather than blame, and build a just culture where engineers feel safe reporting mistakes. Learn to improve application performance by identifying real issues with Azure Application Insights smart detection, reducing meaningless alerts, and understanding server response-time degradation patterns.",
        "objectives": [
            "Configure Azure Application Insights smart detection and interpret performance degradation notifications.",
            "Diagnose and improve application performance using telemetry and profiler data.",
            "Reduce alert fatigue by distinguishing actionable alerts from meaningless noise.",
            "Conduct blameless retrospectives that focus on system improvements rather than individual blame.",
            "Build a just culture where engineers learn from mistakes without fear of punishment.",
        ],
        "units": [
            "Introduction",
            "Examine when to get a notification",
            "Explore how to fix performance issues",
            "Configure smart detection notifications",
            "Improve application performance",
            "Understand server response time degradation",
            "Reduce meaningless and non-actionable alerts",
            "Examine blameless retrospectives",
            "Develop a just culture",
            "Module assessment",
            "Summary",
        ],
    },
    "introduction-to-secure-devops": {
        "summary": "Learn to integrate security throughout your DevOps lifecycle by understanding DevSecOps principles, identifying common vulnerabilities like SQL injection attacks, implementing continuous security validation in your pipelines, conducting effective threat modeling, and using automated security analysis tools like GitHub CodeQL. Build secure applications by embedding security practices into every stage of development and deployment.",
        "objectives": [
            "Identify and understand SQL injection attacks and their impact on application security.",
            "Explain DevSecOps principles and how security integrates throughout the development lifecycle.",
            "Implement security validation at key points in your DevOps pipeline.",
            "Conduct threat modeling to identify and prioritize security risks.",
            "Use GitHub CodeQL for automated security analysis and vulnerability detection.",
        ],
        "units": [
            "Introduction",
            "Describe SQL injection attack",
            "Understand DevSecOps",
            "Explore the secure DevOps pipeline",
            "Explore key validation points",
            "Explore continuous security validation",
            "Understand threat modeling",
            "Explore CodeQL in GitHub",
            "Module assessment",
            "Summary",
        ],
    },
    "implement-open-source-software-azure": {
        "summary": "This module explores how modern software is built with open-source components, corporate concerns about security and licensing, common open-source licenses (MIT, Apache, GPL), license implications for commercial use, and strategies for managing open-source software in enterprise environments.",
        "objectives": [
            "Understand how modern software is built using open-source components and the benefits they provide.",
            "Explain corporate concerns about open-source software including security vulnerabilities, license compliance, and supply chain risks.",
            "Describe common open-source licenses including MIT, Apache, GPL, BSD, and their key characteristics.",
            "Evaluate license implications for commercial software development and understand license compatibility.",
            "Implement strategies for managing open-source components including inventory management, vulnerability scanning, and license compliance.",
        ],
        "units": [
            "Introduction",
            "Explore how software is built",
            "What is open-source software?",
            "Explore corporate concerns with open-source software components",
            "Introduction to open-source licenses",
            "Explore common open-source licenses",
            "Examine license implications and ratings",
            "Module assessment",
            "Summary",
        ],
    },
    "software-composition-analysis": {
        "summary": "This module explains Software Composition Analysis (SCA) fundamentals, inspecting and validating code bases for compliance, implementing GitHub Dependabot for automated vulnerability detection, integrating SCA tools like Mend (WhiteSource), Snyk, and OWASP Dependency-Check into Azure Pipelines, automating container image scanning, and interpreting security alerts from scanning tools.",
        "objectives": [
            "Understand Software Composition Analysis (SCA) and why it's essential for managing open-source dependencies securely.",
            "Inspect and validate code bases for license compliance and security vulnerabilities using automated tools.",
            "Implement GitHub Dependabot to automatically detect vulnerable dependencies and create pull requests for security updates.",
            "Integrate Software Composition Analysis checks into Azure Pipelines to scan dependencies during build and deployment processes.",
            "Examine and configure SCA tools including Mend (WhiteSource), Snyk, OWASP Dependency-Check, and Azure Artifacts upstream sources.",
            "Automate container image scanning to detect vulnerabilities in base images and application dependencies.",
            "Interpret alerts from scanning tools and prioritize remediation based on severity, exploitability, and business impact.",
        ],
        "units": [
            "Introduction",
            "Inspect and validate code bases for compliance",
            "Explore software composition analysis",
            "Implement GitHub Dependabot alerts and security updates",
            "Integrate software composition analysis checks into pipelines",
            "Examine tools for assessing package security and license compliance",
            "Automate container image scanning",
            "Interpret alerts from scanner tools",
            "Module assessment",
            "Summary",
        ],
    },
    "security-monitoring-and-governance": {
        "summary": "This module explores comprehensive security monitoring and governance for Azure DevOps environments. Learn to implement pipeline security, configure Microsoft Defender for Cloud for threat protection and compliance, manage Azure Policy for governance enforcement, secure resources with locks, use Microsoft Defender for Identity threat detection, and integrate GitHub Advanced Security with Microsoft Defender for unified security visibility across your development lifecycle.",
        "objectives": [
            "Implement pipeline security best practices and secure DevOps workflows.",
            "Configure Microsoft Defender for Cloud for threat protection and compliance monitoring.",
            "Create and manage Azure policies for governance and compliance enforcement.",
            "Understand policy initiatives, resource locks, and governance frameworks.",
            "Deploy Microsoft Defender for Identity threat detection.",
            "Integrate GitHub Advanced Security with Microsoft Defender for Cloud.",
            "Configure GitHub Advanced Security features including code scanning, secret scanning, and dependency scanning.",
        ],
        "units": [
            "Introduction",
            "Implement pipeline security",
            "Explore Microsoft Defender for Cloud",
            "Examine Microsoft Defender for Cloud usage scenarios",
            "Explore Azure Policy",
            "Understand policies",
            "Explore initiatives",
            "Explore resource locks",
            "Understand Microsoft Defender for Identity",
            "Integrate GitHub Advanced Security with Microsoft Defender for Cloud",
            "Configure GitHub Advanced Security for GitHub and Azure DevOps",
            "Module assessment",
            "Summary",
        ],
    },
}
