# Fetches instructional unit excerpts from Microsoft Learn for each AZ-400 module in LEARN.
# Run from study-guide/: python fetch_az400_unit_excerpts.py
# Writes az400_learn_unit_excerpts.py (checked in; re-run when Learn content changes).
from __future__ import annotations

import re
import time
import urllib.error
import urllib.request
from html import unescape

from az400_learn_snippets import LEARN

BASE = "https://learn.microsoft.com/en-us/training/modules"
UA = "Mozilla/5.0 (compatible; AZ400-study-guide/1.0; +https://github.com/)"
# Skip assessments; keep summary as short recap
SKIP_SUBSTR = ("knowledge-check",)
MAX_UNITS = 12
MAX_TEXT_PER_UNIT = 950
SLEEP_SEC = 0.35


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read().decode("utf-8", "replace")


def module_units(module_slug: str) -> list[tuple[str, str]]:
    d = fetch(f"{BASE}/{module_slug}/")
    pairs: list[tuple[str, str]] = []

    def scan(pat: str) -> None:
        nonlocal pairs
        for m in re.finditer(pat, d):
            pairs.append((m.group(1), unescape(m.group(2)).strip()))

    # class before href (common)
    scan(
        r'<a class="unit-title[^"]*"[^>]*href="(\d+-[^"]+)"[^>]*>([^<]+)</a>'
    )
    if not pairs:
        scan(
            r'<a[^>]*href="(\d+-[^"]+)"[^>]*class="unit-title[^"]*"[^>]*>([^<]+)</a>'
        )
    # preserve Learn order (HTML order equals path order)
    return pairs


def extract_module_unit_content(html: str) -> str:
    marker = 'id="module-unit-content">'
    start = html.find(marker)
    if start == -1:
        return ""
    sub = html[start + len(marker) :]
    inner_start = 0
    depth = 1
    i = 0
    n = len(sub)
    while i < n:
        if sub.startswith("<div", i):
            depth += 1
            ie = sub.find(">", i)
            if ie == -1:
                break
            i = ie + 1
            continue
        if sub.startswith("</div>", i):
            depth -= 1
            i += 6
            if depth == 0:
                return sub[: i - 6]
            continue
        i += 1
    return ""


def strip_tags(s: str) -> str:
    t = re.sub(r"<[^>]+>", " ", s)
    t = unescape(re.sub(r"\s+", " ", t)).strip()
    return t


def paragraphs_from_inner(inner: str) -> str:
    """Pull text from <p> and key <li> items (Learn often uses lists for objectives)."""
    chunks = [strip_tags(m.group(1)) for m in re.finditer(r"<p[^>]*>(.*?)</p>", inner, re.S | re.I)]
    chunks = [c for c in chunks if c and len(c) > 15]
    for m in re.finditer(r"<li[^>]*>(.*?)</li>", inner, re.S | re.I):
        t = strip_tags(m.group(1))
        if t and len(t) > 15:
            chunks.append(t)
    if not chunks:
        t = strip_tags(inner)
        return t[:MAX_TEXT_PER_UNIT] if t else ""
    text = " ".join(chunks[:12])
    if len(text) > MAX_TEXT_PER_UNIT:
        text = text[: MAX_TEXT_PER_UNIT - 1].rsplit(" ", 1)[0] + "…"
    return text


def should_skip_unit(unit_path: str) -> bool:
    low = unit_path.lower()
    return any(s in low for s in SKIP_SUBSTR)


def excerpt_for_unit(module_slug: str, unit_path: str, title: str) -> dict | None:
    url = f"{BASE}/{module_slug}/{unit_path}/"
    try:
        page = fetch(url)
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, OSError):
        return None
    inner = extract_module_unit_content(page)
    text = paragraphs_from_inner(inner)
    if not text:
        return None
    return {"path": unit_path, "title": title, "url": url, "text": text}


def main() -> None:
    out: dict[str, list[dict]] = {}
    slugs = sorted(LEARN.keys())
    total = len(slugs)
    for si, slug in enumerate(slugs, 1):
        print(f"[{si}/{total}] {slug}")
        try:
            pairs = module_units(slug)
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError, OSError) as e:
            print("  module index failed:", e)
            out[slug] = []
            time.sleep(SLEEP_SEC)
            continue
        rows: list[dict] = []
        for unit_path, title in pairs:
            if should_skip_unit(unit_path):
                continue
            if len(rows) >= MAX_UNITS:
                break
            time.sleep(SLEEP_SEC)
            row = excerpt_for_unit(slug, unit_path, title)
            if row:
                rows.append(row)
                print(f"  ok {unit_path}")
            else:
                print(f"  skip {unit_path} (no text)")
        out[slug] = rows

    path = "az400_learn_unit_excerpts.py"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# AUTO-GENERATED by fetch_az400_unit_excerpts.py — unit paragraph excerpts from Microsoft Learn.\n"
            "# Re-run the fetcher after LEARN slugs change or to refresh copy.\n\n"
            "UNIT_EXCERPTS = "
        )
        f.write(repr(out))
        f.write("\n")
    print("Wrote", path, "modules", len(out))


if __name__ == "__main__":
    main()
